
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "C2S_common.h"
namespace C2S {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_Chat,
               
		Rmi_Send,
               
		Rmi_Quit,
	};

	int g_RmiIDListCount = 3;

}


