  






// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.
   
#pragma once


#include "C2S_common.h"

     
namespace C2S {


	class Stub : public ::Proud::IRmiStub
	{
	public:
               
		virtual bool Chat ( ::Proud::HostID, ::Proud::RmiContext& , const Proud::String & , const int & )		{ 
			return false;
		} 

#define DECRMI_C2S_Chat bool Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num) PN_OVERRIDE

#define DEFRMI_C2S_Chat(DerivedClass) bool DerivedClass::Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num)
#define CALL_C2S_Chat Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num)
#define PARAM_C2S_Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num)
               
		virtual bool Send ( ::Proud::HostID, ::Proud::RmiContext& , const Proud::String & , const int & , const Proud::String & )		{ 
			return false;
		} 

#define DECRMI_C2S_Send bool Send ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num, const Proud::String & sendTime) PN_OVERRIDE

#define DEFRMI_C2S_Send(DerivedClass) bool DerivedClass::Send ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num, const Proud::String & sendTime)
#define CALL_C2S_Send Send ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num, const Proud::String & sendTime)
#define PARAM_C2S_Send ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num, const Proud::String & sendTime)
               
		virtual bool Quit ( ::Proud::HostID, ::Proud::RmiContext& , const Proud::String & )		{ 
			return false;
		} 

#define DECRMI_C2S_Quit bool Quit ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & dlg) PN_OVERRIDE

#define DEFRMI_C2S_Quit(DerivedClass) bool DerivedClass::Quit ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & dlg)
#define CALL_C2S_Quit Quit ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & dlg)
#define PARAM_C2S_Quit ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & dlg)
 
		virtual bool ProcessReceivedMessage(::Proud::CReceivedMessage &pa, void* hostTag) PN_OVERRIDE;
		static const PNTCHAR* RmiName_Chat;
		static const PNTCHAR* RmiName_Send;
		static const PNTCHAR* RmiName_Quit;
		static const PNTCHAR* RmiName_First;
		virtual ::Proud::RmiID* GetRmiIDList() PN_OVERRIDE { return g_RmiIDList; }
		virtual int GetRmiIDListCount() PN_OVERRIDE { return g_RmiIDListCount; }
	};

#ifdef SUPPORTS_CPP11 
	
	class StubFunctional : public Stub 
	{
	public:
               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const Proud::String & , const int & ) > Chat_Function;
		virtual bool Chat ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num) 
		{ 
			if (Chat_Function==nullptr) 
				return true; 
			return Chat_Function(remote,rmiContext, str, num); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const Proud::String & , const int & , const Proud::String & ) > Send_Function;
		virtual bool Send ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & str, const int & num, const Proud::String & sendTime) 
		{ 
			if (Send_Function==nullptr) 
				return true; 
			return Send_Function(remote,rmiContext, str, num, sendTime); 
		}

               
		std::function< bool ( ::Proud::HostID, ::Proud::RmiContext& , const Proud::String & ) > Quit_Function;
		virtual bool Quit ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & dlg) 
		{ 
			if (Quit_Function==nullptr) 
				return true; 
			return Quit_Function(remote,rmiContext, dlg); 
		}

	};
#endif

}


