
// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "S2C_common.h"
namespace S2C {


	::Proud::RmiID g_RmiIDList[] = {
               
		Rmi_recvString,
	};

	int g_RmiIDListCount = 1;

}


