




// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.


#include "S2C_proxy.h"

namespace S2C {


        
	bool Proxy::recvString ( ::Proud::HostID remote, ::Proud::RmiContext& rmiContext , const Proud::String & txt, const int & num)	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_recvString;
__msg.Write(__msgid); 
	
__msg << txt;
__msg << num;
		
		return RmiSend(&remote,1,rmiContext,__msg,
			RmiName_recvString, (::Proud::RmiID)Rmi_recvString);
	}

	bool Proxy::recvString ( ::Proud::HostID *remotes, int remoteCount, ::Proud::RmiContext &rmiContext, const Proud::String & txt, const int & num)  	{
		::Proud::CMessage __msg;
__msg.UseInternalBuffer();
__msg.SetSimplePacketMode(m_core->IsSimplePacketMode());

::Proud::RmiID __msgid=(::Proud::RmiID)Rmi_recvString;
__msg.Write(__msgid); 
	
__msg << txt;
__msg << num;
		
		return RmiSend(remotes,remoteCount,rmiContext,__msg,
			RmiName_recvString, (::Proud::RmiID)Rmi_recvString);
	}
#ifdef USE_RMI_NAME_STRING
const PNTCHAR* Proxy::RmiName_recvString =_PNT("recvString");
#else
const PNTCHAR* Proxy::RmiName_recvString =_PNT("");
#endif
const PNTCHAR* Proxy::RmiName_First = RmiName_recvString;

}



